# 1UGH HDXRank YAML configuration

GeneralParameters:
  RootDir: ./example/1UGH_docking
  EmbeddingDir: embedding_files
  PDBDir: structures
  hhmDir: hhm_files
  HDXDir: HDX_files
  pepGraphDir: graph_ensemble_GearNet
  Mode: Predict # options: Train, Predict
  TaskFile: null # provide only in train mode (read xlsx file and search hdx data under HDXDir)
  HDX_File: BioChem_UNGUGI

# Construct peptide graphs
TaskParameters: 
  Switch: True
  #EmbeddingToUse: 1UGH  # embedding file name to use for prediction
  PepRange: null # used to filter HDX peptides, if not specified, all peptides will be used
  HDX_Chains:
  # record the chains in the complex PDB that contain HDX data
  # protein, state : used for extracting HDX data from the HDX file
  # correction_value: used for match PDB file index with HDX file index, HDX residue index + correction = PDB residue index
  # structure_file: for both apo and complex
    - Entity: 1AKZ_1UGH
      apo_state:
        protein: hUNG
        state: apo
        chainID: E
        correction_value: -9
        structure_file: 1AKZ
      complex_state:
        protein: hUNG-UGI
        state: complex
        chainID: E
        correction_value: -9
        structure_file: 1UGH

    - Entity: 1UGI_1UGH
      apo_state:
        protein: UGI
        state: apo
        chainID: I
        correction_value: 0
        structure_file: 1UGI
      complex_state:
        protein: UGI-hUNG
        state: complex
        chainID: I
        correction_value: 0
        structure_file: 1UGH
  # add more chains if needed...

# Predict RFU for peptide graphs
PredictionParameters:
  Switch: True
  ModelDir: ../../models/prev_models+hse
  PredDir: predictions
  ModelList:
    - HDXRank_GN56_v0
    - HDXRank_GN56_v1
    - HDXRank_GN56_v2
    - HDXRank_GN56_v3
    - HDXRank_GN56_v4
  CudaID: 1
  BatchSize: 64

# Calculate HDXRank scores
ScorerParameters:
  Switch: True
  save_dir: "results/scores"
  protein_name: "1UGH"
  pred_cluster: 2 # specify the cluster of predictions to use for scoring, [0/1/2]
  timepoints: [1000, 1001] # specify time range (in seconds) of hdx data used to calcualte scores
  plot_hdx: True # whether to plot HDX RFU data
  
TrainParameters:
  SaveDir: "./models"
  Epochs: 100
  CudaID: 1
  TrainValSplit: 0.2
  BatchSize: 16
  Seeds: [42, 43, 44, 45, 46]
  Repeat: 5
  ModelName: "HDXRank" 
  InputDim: 56
  HiddenDims: [64, 64, 64]

# Modify graph construction parameters for training
GraphParameters:
  RadiusMax: 8.0
  SeqMin: 3
  GraphType: GearNet
  EmbeddingType: manual
  MaxLen: 30