# 1UGH HDXRank YAML configuration

GeneralParameters:
  RootDir: ./example/8F7A_docking
  EmbeddingDir: embedding_files
  PDBDir: structures
  hhmDir: hhm_files
  HDXDir: HDX_files
  pepGraphDir: graph_ensemble_GearNet
  Mode: single
  TaskFile: null 
  HDX_File: PXD037571

# Construct peptide graphs
TaskParameters: 
  Switch: True
  PepRange: null 
  HDX_Chains:
    - Entity: 8F7A
      apo_state:
        protein: RanGTP
        state: Ran
        chainID: B
        correction_value: 0
        hhm_prefix: 8F7A_B
      complex_state:
        protein: RanGTP
        state: Imp9+Ran
        chainID: B
        correction_value: 0
        hhm_prefix: 8F7A
      ref_structure: 8F7A_B

    - Entity: 8F7A
      apo_state:
        protein: Imp9
        state: Imp9
        chainID: A
        correction_value: 0
        hhm_prefix: 8F7A_A
      complex_state:
        protein: Imp9
        state: Imp9+Ran
        chainID: A
        correction_value: 0
        hhm_prefix: 8F7A
      ref_structure: 8F7A_A

# Predict RFU for peptide graphs
PredictionParameters:
  Switch: True
  ModelDir: ../../models
  PredDir: predictions
  ModelList:
    - HDXRank_GN56_v0
    - HDXRank_GN56_v1
    - HDXRank_GN56_v2
    - HDXRank_GN56_v3
    - HDXRank_GN56_v4
  CudaID: 1
  BatchSize: 64

# Calculate HDXRank scores
ScorerParameters:
  Switch: True
  save_dir: "results"
  protein_name: "8F7A"
  pred_cluster: 1
  timepoints: null
  plot_hdx: True

TrainParameters:
  SaveDir: "./models"
  Epochs: 100
  CudaID: 1
  TrainValSplit: 0.2
  BatchSize: 16
  Seeds: [42, 43, 44, 45, 46]
  Repeat: 5
  ModelName: "HDXRank" 
  InputDim: 56
  HiddenDims: [64, 64, 64]

# Modify graph construction parameters for training
GraphParameters:
  RadiusMax: 8.0
  SeqMin: 3
  GraphType: GearNet
  EmbeddingType: manual
  MaxLen: 30